name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Installation de graphviz
      run: sudo apt-get install -y graphviz
    - name: Lancement graphviz
      run: ./run2.sh *.dot
    - name: Upload du r√©sultat
      uses: actions/upload-artifact@v4
      with:
        name: resultat-graphviz
        path: /*.svg

